//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePushSnap.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnePushSnap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon _1pushsnap_app {
            get {
                object obj = ResourceManager.GetObject("_1pushsnap_app", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon _1pushsnap_off {
            get {
                object obj = ResourceManager.GetObject("_1pushsnap_off", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon _1pushsnap_on {
            get {
                object obj = ResourceManager.GetObject("_1pushsnap_on", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   1 Push Snap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string context_menu_item_close {
            get {
                return ResourceManager.GetString("context_menu_item_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string context_menu_item_image_format {
            get {
                return ResourceManager.GetString("context_menu_item_image_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string context_menu_item_information {
            get {
                return ResourceManager.GetString("context_menu_item_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save To... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string context_menu_item_save {
            get {
                return ResourceManager.GetString("context_menu_item_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start - 1 push screenshot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string context_menu_item_start_1pushsnap {
            get {
                return ResourceManager.GetString("context_menu_item_start_1pushsnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start - Ignore key type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string context_menu_item_start_igg_keyboard {
            get {
                return ResourceManager.GetString("context_menu_item_start_igg_keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start - Ignore mouse click に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string context_menu_item_start_igg_mouse {
            get {
                return ResourceManager.GetString("context_menu_item_start_igg_mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string context_menu_item_stop {
            get {
                return ResourceManager.GetString("context_menu_item_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1PushSnap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string file_prefix {
            get {
                return ResourceManager.GetString("file_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BMP|GIF|JPG|PNG に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string image_format {
            get {
                return ResourceManager.GetString("image_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click OK for unlocking keyboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string message_igg_keyboard {
            get {
                return ResourceManager.GetString("message_igg_keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press OK for unlocking mouse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string message_igg_mouse {
            get {
                return ResourceManager.GetString("message_igg_mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screenshot image is saved in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string message_image_type_label {
            get {
                return ResourceManager.GetString("message_image_type_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The folder you specified does not exist.
        ///Your file is saved to
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string message_non_existent_folder {
            get {
                return ResourceManager.GetString("message_non-existent_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screenshot images are saved to 
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string message_save_folder {
            get {
                return ResourceManager.GetString("message_save_folder", resourceCulture);
            }
        }
    }
}
